---
# tasks file for download_and_deploy_containerized_application/
- name: Create CDaaS-Demo-App container
  docker_container:
    name: "CDaaS-Demo-App"
    image: {{ CI_CONTAINER_IMAGE }}:{{ CI_COMMIT_REF_NAME }}
    state: started
    recreate: yes #Use with present and started states to force the re-creation of an existing container.
    exposed_ports:
      - "8080"
